
[project]
name = "verilator-dspsim"
version = "5.52.1"
description = "A Python wrapper around an installation of Verilator."
readme = "README.md"
authors = [{ name = "Frank Sodari" }]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]
requires-python = ">=3.12"
dependencies = []

[project.urls]
Homepage = "https://github.com/fsodari/verilator-python"

[project.scripts]
verilator-dspsim = "verilator:_verilator_cli"

[build-system]
requires = ["scikit-build-core>=1.0.3"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.version = ">=3.26.1"
cmake.build-type = "Release"
build.verbose = true
minimum-version = "build-system.requires"
build-dir = "build"

# # Supporting cp312 stable abi.
# wheel.py-api = "cp312"

wheel.packages = ["src/verilator"]
# This needs to be set so that verilator installs at site-packages/verilator_dspsim
wheel.install-dir = "verilator"


[tool.cibuildwheel]
# 2_28 seems to work well with all the tools.
# manylinux-x86_64-image = "manylinux_2_28"
build-verbosity = 1
# Run pytest to ensure that the package was correctly built
test-command = "pytest {project}/tests"
test-requires = "pytest"

# 64 bit builds
archs = ["auto64"]

# build = ["cp312-*"]
# Don't build arm. Use only > cp39, no PyPy. Not using musl anywhere so no musl (it works though)
skip = ["*-win_arm64", "*musllinux*"]

# manylinux builds
[tool.cibuildwheel.linux]
before-all = [
    "yum install -y flex",
    "yum install -y bison",
    "yum install -y lz4",
    "yum install -y lz4-devel",
    # "yum install -y ccache",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.16.7",
    "scikit-build-core>=1.0.3"
]
